# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8f88da282a997556f174ebb418854dbd339be8836f08d963a79723a39001858b9b28a959fb29450657742253a61ddd13c036382dc31f84e7a91446c227ae8de5

test:
  secret_key_base: 67d090e0da1ec64fa5cda3a7294f189bea007f392c6027e4508ef0c6ee107cee103aeae958169d72c97b96938f4e962ccba0b90f7462bec91fd3d011417bdbb2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
